# Adapt this sample to your database configuration
# and then rename it into database.yml
# See http://stackoverflow.com/questions/2856996/git-and-rails-ignore-database-yml

# POSTGRES
# development:
#   host: localhost
#   adapter: postgresql
#   encoding: unicode
#   database: familyMe_development
#   pool: 5
#   min_messages: WARNING

# SQLITE3
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   timeout: 5000

# MYSQL
development:
  adapter: mysql2
  encoding: utf8
  database: familyMe_development
  host: 127.0.0.1
  port: 3306

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

cucumber:
  <<: *test
